/**
 * @author: Moritz Jäger
 * @description: Die Typescript-Datei testApp.ts bildet simpele Tests des backends (app.ts) ab
 */

import { convert, convertIliasQTIToMoodleXML, convertMoodleXMLToIliasQTI, isMoodleXML } from "./app";
import { strict as assert } from 'assert';

const xmlString: string = `
<?xml version="1.0" encoding="UTF-8"?>
<quiz>
<!-- question: 5813  -->
<question type="multichoice">
<name>
<text>Eine Multiple Choice Frage</text>
</name>
<questiontext format="html">
<text><![CDATA[<p dir="ltr" style="text-align: left;">Hier steht der Fragetext.<br></p>]]></text>
</questiontext>
<generalfeedback format="html">
<text></text>
</generalfeedback>
<defaultgrade>1</defaultgrade>
<penalty>0.3333333</penalty>
<hidden>0</hidden>
<idnumber></idnumber>
<single>false</single>
<shuffleanswers>true</shuffleanswers>
<answernumbering>abc</answernumbering>
<showstandardinstruction>1</showstandardinstruction>
<correctfeedback format="html">
<text>Die Antwort ist richtig.</text>
</correctfeedback>
<partiallycorrectfeedback format="html">
<text>Die Antwort ist teilweise richtig.</text>
</partiallycorrectfeedback>
<incorrectfeedback format="html">
<text>Die Antwort ist falsch.</text>
</incorrectfeedback>
<shownumcorrect/>
<answer fraction="100" format="html">
<text><![CDATA[<p dir="ltr" style="text-align: left;">Antwort A (richtige Antwort)<br></p>]]></text>
<feedback format="html">
<text></text>
</feedback>
</answer>
<answer fraction="-100" format="html">
<text><![CDATA[<p dir="ltr" style="text-align: left;">Antwort B (falsche Antwort)<br></p>]]></text>
<feedback format="html">
<text></text>
</feedback>
</answer>
</question>
</quiz>
`;
const qtiString: string = `
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE questestinterop SYSTEM "ims_qtiasiv1p2p1.dtd">
<!--Generated by ILIAS XmlWriter-->
<questestinterop>
	<item ident="il_0_qst_57" title="Eine MC-Frage" maxattempts="0">
		<qticomment>MC-Frage zum ausprobieren verschiedener Optionen</qticomment>
		<duration>P0Y0M0DT1H2M3S</duration>
		<itemmetadata>
			<qtimetadata>
				<qtimetadatafield>
					<fieldlabel>ILIAS_VERSION</fieldlabel>
					<fieldentry>6.9 2021-04-30</fieldentry>
				</qtimetadatafield>
				<qtimetadatafield>
					<fieldlabel>QUESTIONTYPE</fieldlabel>
					<fieldentry>MULTIPLE CHOICE QUESTION</fieldentry>
				</qtimetadatafield>
				<qtimetadatafield>
					<fieldlabel>AUTHOR</fieldlabel>
					<fieldentry>Karen Czerwonatis</fieldentry>
				</qtimetadatafield>
				<qtimetadatafield>
					<fieldlabel>additional_cont_edit_mode</fieldlabel>
					<fieldentry>default</fieldentry>
				</qtimetadatafield>
				<qtimetadatafield>
					<fieldlabel>externalId</fieldlabel>
					<fieldentry>638dc9f37c4700.54589420</fieldentry>
				</qtimetadatafield>
				<qtimetadatafield>
					<fieldlabel>ilias_lifecycle</fieldlabel>
					<fieldentry>sharable</fieldentry>
				</qtimetadatafield>
				<qtimetadatafield>
					<fieldlabel>lifecycle</fieldlabel>
					<fieldentry>final</fieldentry>
				</qtimetadatafield>
				<qtimetadatafield>
					<fieldlabel>thumb_size</fieldlabel>
					<fieldentry/>
				</qtimetadatafield>
				<qtimetadatafield>
					<fieldlabel>feedback_setting</fieldlabel>
					<fieldentry>1</fieldentry>
				</qtimetadatafield>
				<qtimetadatafield>
					<fieldlabel>singleline</fieldlabel>
					<fieldentry>0</fieldentry>
				</qtimetadatafield>
			</qtimetadata>
		</itemmetadata>
		<presentation label="Eine MC-Frage">
			<flow>
				<material>
					<mattext texttype="text/plain">Wie viele Optionen habe ich noch nicht probiert?</mattext>
				</material>
				<response_lid ident="MCMR" rcardinality="Multiple">
					<render_choice shuffle="No" minnumber="0" maxnumber="2">
						<response_label ident="0">
							<material>
								<mattext texttype="text/plain">Antwort 1</mattext>
							</material>
						</response_label>
						<response_label ident="1">
							<material>
								<mattext texttype="text/plain">Antwort 2</mattext>
							</material>
						</response_label>
						<response_label ident="2">
							<material>
								<mattext texttype="text/plain">extralange Antwort 3 - Mehrzeilige Antworten machen ja nur Sinn, wenn die Antworten auch lang genugn sind für mehrere Zeilen</mattext>
							</material>
						</response_label>
					</render_choice>
				</response_lid>
			</flow>
		</presentation>
		<resprocessing>
			<outcomes>
				<decvar></decvar>
			</outcomes>
			<respcondition continue="Yes">
				<conditionvar>
					<varequal respident="MCMR">0</varequal>
				</conditionvar>
				<setvar action="Add">2</setvar>
				<displayfeedback feedbacktype="Response" linkrefid="response_0"/>
			</respcondition>
			<respcondition continue="Yes">
				<conditionvar>
					<not>
						<varequal respident="MCMR">0</varequal>
					</not>
				</conditionvar>
				<setvar action="Add">-1</setvar>
			</respcondition>
			<respcondition continue="Yes">
				<conditionvar>
					<varequal respident="MCMR">1</varequal>
				</conditionvar>
				<setvar action="Add">1</setvar>
				<displayfeedback feedbacktype="Response" linkrefid="response_1"/>
			</respcondition>
			<respcondition continue="Yes">
				<conditionvar>
					<not>
						<varequal respident="MCMR">1</varequal>
					</not>
				</conditionvar>
				<setvar action="Add">-2</setvar>
			</respcondition>
			<respcondition continue="Yes">
				<conditionvar>
					<varequal respident="MCMR">2</varequal>
				</conditionvar>
				<setvar action="Add">-1</setvar>
				<displayfeedback feedbacktype="Response" linkrefid="response_2"/>
			</respcondition>
			<respcondition continue="Yes">
				<conditionvar>
					<not>
						<varequal respident="MCMR">2</varequal>
					</not>
				</conditionvar>
				<setvar action="Add">0</setvar>
			</respcondition>
			<respcondition continue="Yes">
				<conditionvar>
					<varequal respident="MCMR">0</varequal>
					<varequal respident="MCMR">1</varequal>
					<not>
						<varequal respident="MCMR">2</varequal>
					</not>
				</conditionvar>
				<displayfeedback feedbacktype="Response" linkrefid="response_allcorrect"/>
			</respcondition>
			<respcondition continue="Yes">
				<conditionvar>
					<not>
						<varequal respident="MCMR">0</varequal>
					</not>
					<or>
						<not>
							<varequal respident="MCMR">1</varequal>
						</not>
					</or>
					<or>
						<varequal respident="MCMR">2</varequal>
					</or>
				</conditionvar>
				<displayfeedback feedbacktype="Response" linkrefid="response_onenotcorrect"/>
			</respcondition>
		</resprocessing>
		<itemfeedback ident="response_0" view="All">
			<flow_mat>
				<material>
					<mattext texttype="text/plain">Feedback zu Antwort 1</mattext>
				</material>
			</flow_mat>
		</itemfeedback>
		<itemfeedback ident="response_1" view="All">
			<flow_mat>
				<material>
					<mattext texttype="text/plain">Feedback zu Antwort 2</mattext>
				</material>
			</flow_mat>
		</itemfeedback>
		<itemfeedback ident="response_2" view="All">
			<flow_mat>
				<material>
					<mattext texttype="text/plain">Feedback zu Antwort 3</mattext>
				</material>
			</flow_mat>
		</itemfeedback>
		<itemfeedback ident="response_allcorrect" view="All">
			<flow_mat>
				<material>
					<mattext texttype="text/plain">Feedback bei richtiger Lösung</mattext>
				</material>
			</flow_mat>
		</itemfeedback>
		<itemfeedback ident="response_onenotcorrect" view="All">
			<flow_mat>
				<material>
					<mattext texttype="text/plain">Feedback, wenn mindestens eine Antwort falsch ist</mattext>
				</material>
			</flow_mat>
		</itemfeedback>
	</item>
</questestinterop>
`;


assert(isMoodleXML(xmlString) == true);
assert(isMoodleXML(qtiString) == false);
//console.log(convertMoodleXMLToIliasQTI(xmlString));
//console.log(convertIliasQTIToMoodleXML(qtiString));

console.log(convert(qtiString));
